/**
 * Generated by:         ecc v0.3beta
 * Generation timestamp: Fri Feb 28 20:08:19 2014
 */
#include <string>
#include <sstream>
using namespace std;

#include "codes.h"

namespace {
    static const string notfound="";
    static const string warningcode_NoWarning = "NoWarning";
    static const string warningcode_DuplicateValue = "DuplicateValue";
    static const string warningcode_l_DuplicateValue = "Duplicate member value on #enum";
    static const string errorcode_NoError = "NoError";
    static const string errorcode_DuplicateEnum = "DuplicateEnum";
    static const string errorcode_FlagsAndLongstrings = "FlagsAndLongstrings";
    static const string errorcode_l_DuplicateEnum = "Duplicate typename #enum";
    static const string errorcode_l_FlagsAndLongstrings = "Illegal combination of flags and longstrings on #enum";
}

namespace ecc {

    const string& getstr_warningcode(warningcode v, bool longStr)
    {
        switch (v) {
            case NoWarning:
                return warningcode_NoWarning;
            case DuplicateValue:
                return (longStr)?warningcode_l_DuplicateValue:warningcode_DuplicateValue;
            default: 
                return notfound;
        }
    }

    const string& getstr_errorcode(errorcode v, bool longStr)
    {
        switch (v) {
            case NoError:
                return errorcode_NoError;
            case DuplicateEnum:
                return (longStr)?errorcode_l_DuplicateEnum:errorcode_DuplicateEnum;
            case FlagsAndLongstrings:
                return (longStr)?errorcode_l_FlagsAndLongstrings:errorcode_FlagsAndLongstrings;
            default: 
                return notfound;
        }
    }
}
