/**
 * Generated by:         ecc v0.3beta
 * Generation timestamp: Sat Mar  1 07:46:01 2014
 */
#include <string>
#include <sstream>
using namespace std;

#include "codes.h"

namespace {
    static const string notfound="";
    static const string ecc_warningcode_NoWarning = "NoWarning";
    static const string ecc_warningcode_DuplicateValue = "DuplicateValue";
    static const string ecc_warningcode_l_DuplicateValue = "Duplicate member value on #enum";
    static const string ecc_errorcode_NoError = "NoError";
    static const string ecc_errorcode_SyntaxError = "SyntaxError";
    static const string ecc_errorcode_DuplicateEnum = "DuplicateEnum";
    static const string ecc_errorcode_FlagsAndLongstrings = "FlagsAndLongstrings";
    static const string ecc_errorcode_MissingSemicolon = "MissingSemicolon";
    static const string ecc_errorcode_MalformedEnumdef = "MalformedEnumdef";
    static const string ecc_errorcode_l_SyntaxError = "Syntax error";
    static const string ecc_errorcode_l_DuplicateEnum = "Duplicate typename #enum";
    static const string ecc_errorcode_l_FlagsAndLongstrings = "Illegal combination of flags and longstrings on #member";
    static const string ecc_errorcode_l_MissingSemicolon = "Missing semicolon following #enum";
    static const string ecc_errorcode_l_MalformedEnumdef = "Malformed enum definition";
}

namespace ecc {

    const string& getstr_warningcode(warningcode v, bool longStr)
    {
        switch (v) {
            case NoWarning:
                return ecc_warningcode_NoWarning;
            case DuplicateValue:
                return (longStr)?ecc_warningcode_l_DuplicateValue:ecc_warningcode_DuplicateValue;
            default: 
                return notfound;
        }
    }

    const string& getstr_errorcode(errorcode v, bool longStr)
    {
        switch (v) {
            case NoError:
                return ecc_errorcode_NoError;
            case SyntaxError:
                return (longStr)?ecc_errorcode_l_SyntaxError:ecc_errorcode_SyntaxError;
            case DuplicateEnum:
                return (longStr)?ecc_errorcode_l_DuplicateEnum:ecc_errorcode_DuplicateEnum;
            case FlagsAndLongstrings:
                return (longStr)?ecc_errorcode_l_FlagsAndLongstrings:ecc_errorcode_FlagsAndLongstrings;
            case MissingSemicolon:
                return (longStr)?ecc_errorcode_l_MissingSemicolon:ecc_errorcode_MissingSemicolon;
            case MalformedEnumdef:
                return (longStr)?ecc_errorcode_l_MalformedEnumdef:ecc_errorcode_MalformedEnumdef;
            default: 
                return notfound;
        }
    }
}
