/**
 * Generated by:         ecc v0.3beta
 * Generation timestamp: Fri Feb 28 20:33:54 2014
 */

#ifndef _HG_CODES_H_
#define _HG_CODES_H_


namespace ecc {

    typedef enum {
        NoWarning=0,
        DuplicateValue=1
    } warningcode;

    typedef enum {
        NoError=0,
        DuplicateEnum=1,
        FlagsAndLongstrings=2
    } errorcode;

    extern const string& getstr_warningcode(warningcode v, bool longStr=false);
    extern const string& getstr_errorcode(errorcode v, bool longStr=false);
}

#endif
