/**
 * Generated by:         ecc v0.3beta
 * Generation timestamp: Fri Feb 28 20:33:54 2014
 */
#include <string>
#include <sstream>
using namespace std;

#include "codes.h"

namespace {
    static const string notfound="";
    static const string ecc_warningcode_NoWarning = "NoWarning";
    static const string ecc_warningcode_DuplicateValue = "DuplicateValue";
    static const string ecc_warningcode_l_DuplicateValue = "Duplicate member value on #enum";
    static const string ecc_errorcode_NoError = "NoError";
    static const string ecc_errorcode_DuplicateEnum = "DuplicateEnum";
    static const string ecc_errorcode_FlagsAndLongstrings = "FlagsAndLongstrings";
    static const string ecc_errorcode_l_DuplicateEnum = "Duplicate typename #enum";
    static const string ecc_errorcode_l_FlagsAndLongstrings = "Illegal combination of flags and longstrings on #member";
}

namespace ecc {

    const string& getstr_warningcode(warningcode v, bool longStr)
    {
        switch (v) {
            case NoWarning:
                return ecc_warningcode_NoWarning;
            case DuplicateValue:
                return (longStr)?ecc_warningcode_l_DuplicateValue:ecc_warningcode_DuplicateValue;
            default: 
                return notfound;
        }
    }

    const string& getstr_errorcode(errorcode v, bool longStr)
    {
        switch (v) {
            case NoError:
                return ecc_errorcode_NoError;
            case DuplicateEnum:
                return (longStr)?ecc_errorcode_l_DuplicateEnum:ecc_errorcode_DuplicateEnum;
            case FlagsAndLongstrings:
                return (longStr)?ecc_errorcode_l_FlagsAndLongstrings:ecc_errorcode_FlagsAndLongstrings;
            default: 
                return notfound;
        }
    }
}
