/**
 * Generated by:         ecc v0.3beta
 * Generation timestamp: Sat Mar  1 07:46:01 2014
 */

#ifndef _HG_CODES_H_
#define _HG_CODES_H_


namespace ecc {

    typedef enum {
        NoWarning=0,
        DuplicateValue=1
    } warningcode;

    typedef enum {
        NoError=0,
        SyntaxError=1,
        DuplicateEnum=2,
        FlagsAndLongstrings=3,
        MissingSemicolon=4,
        MalformedEnumdef=5
    } errorcode;

    extern const string& getstr_warningcode(warningcode v, bool longStr=false);
    extern const string& getstr_errorcode(errorcode v, bool longStr=false);
}

#endif
