/*******************************************************************************
 * WARNING: This file was generated by a tool! Do not hand modify unless you
 *          know what you are doing. 
 *
 * Generated by: ecc v0.0alpha
 * Generated on: 5th February 2014, 5:08pm
 * Source file : enums.def
 */

#include <string>

/*******************************************************************************
 * enum my_t
 */
typedef enum
{
    firstValue=0,
    secondValue=1
} my_t;

namespace
{
    static const std::string notfound="";
    static const std::string my_t_FirstValue = "firstValue";
    static const std::string my_t_SecondValue = "secondValue";
}

const std::string& getstr_my_t(my_t v)
{
    switch (v)
    {
    case firstValue:
	return my_t_FirstValue;
    case secondValue:
	return my_t_SecondValue;
    default:
	return notfound;
    }
}
