/**
 * Generated by:         ecc v0.3beta
 * Generation timestamp: Wed Feb 26 21:37:11 2014
 */
#include <string>
#include <sstream>
using namespace std;

#include "warn.h"

namespace {
    static const string notfound="";
    static const string ecc_warningcode_NoWarning = "NoWarning";
    static const string ecc_warningcode_DuplicateValue = "DuplicateValue";
    static const string ecc_warningcode_l_DuplicateValue = "Duplicate member value on #enum at line #line";
}

namespace ecc {

    const string& getstr_warningcode(warningcode v, bool longStr)
    {
        switch (v) {
            case NoWarning:
                return ecc_warningcode_NoWarning;
            case DuplicateValue:
                return (longStr)?ecc_warningcode_l_DuplicateValue:ecc_warningcode_DuplicateValue;
            default: 
                return notfound;
        }
    }
}
