/**
 * Generated by:         ecc v0.3beta
 * Generation timestamp: Wed Feb 26 21:37:11 2014
 */

#ifndef _HG_WARN_H_
#define _HG_WARN_H_


namespace ecc {

    typedef enum {
        NoWarning=0,
        DuplicateValue=1
    } warningcode;

    extern const string& getstr_warningcode(warningcode v, bool longStr=false);
}

#endif
