/**
 * Generated by:         ecc v0.2beta
 * Generation timestamp: Tue Feb 25 18:57:04 2014
 */

#ifndef _HG_WARN_H_
#define _HG_WARN_H_


namespace ecc {

    typedef enum {
        NoWarning=0,
        DuplicateValue=1
    } warningcode;

    extern const string& getstr_warningcode(warningcode v, bool longStr=false);
}

#endif
